import type {
  CertificationArea,
  GeneralCourseDef,
  GeneralEducationRequirements,
  MajorCourseDef,
  Requirements,
} from "./types";
import { majorCourseEquivalentsByCode } from "./majorCourseEquivalents";
import { DEFAULT_DEPARTMENT, DEFAULT_SCHOOL } from "./academicUnits";

// 컴퓨터공학과 22학번 기준. 출처: 순천대학교 「2022학년도 교육과정」책자
// ([별표 1] 학과·학부(전공)별 졸업소요학점 구성표 p.26, 컴퓨터공학과 전공 교육과정편성표 p.157),
// 「순천대학교 졸업자격 인증제 운영 지침」(2015.5.18 제정, 2019.11.28 개정).
// kind는 2022학번 졸업요건 구분을 유지하며, 2026 교육과정에만 있는 추가 과목은 해당 표의 선택 구분을 따른다.
const majorCourseBase22: Omit<MajorCourseDef, "equivalents">[] = [
  { id: "c_cs", code: "CS0614", name: "컴퓨터과학", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "c_ds", code: "CS0603", name: "자료구조", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "c_ca", code: "CS0615", name: "컴퓨터구조", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "c_db", code: "CS0617", name: "데이터베이스", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "c_os", code: "CS0610", name: "운영체제", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "c_pl", code: "CS0618", name: "프로그래밍언어론", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "m_cs0863", code: "CS0863", name: "HCI(AR/VR/XR)", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "c_di", code: "CS0621", name: "디지털이미징", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "m_cs0715", code: "CS0715", name: "이매지니어프로젝트Ⅰ", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "c_sad", code: "CS0605", name: "시스템분석및설계", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "c_sec", code: "CS0622", name: "정보보호", credits: 3, kind: "required", curriculumYear: 2026 },
  { id: "m_cs0716", code: "CS0716", name: "이매지니어프로젝트Ⅱ", credits: 3, kind: "required", curriculumYear: 2026 },

  { id: "e_acp", code: "CS0855", name: "고급컴퓨터프로그래밍", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs0623", code: "CS0623", name: "이산수학", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_ic0701", code: "IC0701", name: "SW 전공영어", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "e_mp", code: "CS0856", name: "모바일프로그래밍", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs0862", code: "CS0862", name: "OSS개론", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs0860", code: "CS0860", name: "어드벤쳐디자인", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs2001", code: "CS2001", name: "멀티패러다임프로그래밍", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "e_mm", code: "CS0667", name: "멀티미디어", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "e_ls", code: "CS0857", name: "리눅스시스템", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "e_alg", code: "CS0669", name: "컴퓨터알고리즘", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs0865", code: "CS0865", name: "블록체인", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "e_wp", code: "CS0858", name: "웹프로그래밍", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "e_comp", code: "CS0672", name: "컴파일러", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs0864", code: "CS0864", name: "머신러닝", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs2003", code: "CS2003", name: "객체지향프로그래밍", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs2002", code: "CS2002", name: "산학협력프로젝트", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs2005", code: "CS2005", name: "NovaSW취창업1", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_cs2004", code: "CS2004", name: "NovaSW취창업2", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "e_cv", code: "CS0661", name: "컴퓨터비전", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "e_ai", code: "CS0662", name: "인공지능", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "e_se", code: "CS0663", name: "소프트웨어공학", credits: 3, kind: "elective", curriculumYear: 2026 },
  { id: "m_ic0683", code: "IC0683", name: "딥러닝기초", credits: 3, kind: "elective", curriculumYear: 2026 },
];

export const majorCourses22: MajorCourseDef[] = majorCourseBase22.map((course) => ({
  ...course,
  equivalents: majorCourseEquivalentsByCode[course.code] ?? [],
}));

export const generalCourses22: GeneralCourseDef[] = [
  { id: "g_xg0800", code: "XG0800", name: "대학생활과 목표설정", credits: 1, areaId: "common_foundation", areaName: "공통교양-기초" },
  { id: "g_xg0700", code: "XG0700", name: "독서와 표현", credits: 2, areaId: "common_foundation", areaName: "공통교양-기초" },
  { id: "g_xg0701", code: "XG0701", name: "사고와 글쓰기", credits: 2, areaId: "common_foundation", areaName: "공통교양-기초" },
  { id: "g_xg0702", code: "XG0702", name: "정량적사고와 컴퓨팅사고", credits: 2, areaId: "common_foundation", areaName: "공통교양-기초" },

  { id: "g_xg0703", code: "XG0703", name: "문학과삶", credits: 3, areaId: "common_core_humanities", areaName: "공통교양-핵심/인문학" },
  { id: "g_xg0704", code: "XG0704", name: "현대예술문화", credits: 3, areaId: "common_core_humanities", areaName: "공통교양-핵심/인문학" },
  { id: "g_xg0705", code: "XG0705", name: "한국의 역사", credits: 3, areaId: "common_core_humanities", areaName: "공통교양-핵심/인문학" },
  { id: "g_xg0706", code: "XG0706", name: "철학산책", credits: 3, areaId: "common_core_humanities", areaName: "공통교양-핵심/인문학" },
  { id: "g_xg0707", code: "XG0707", name: "글로벌 시민정치", credits: 3, areaId: "common_core_social", areaName: "공통교양-핵심/사회과학" },
  { id: "g_xg0708", code: "XG0708", name: "경제의 이해", credits: 3, areaId: "common_core_social", areaName: "공통교양-핵심/사회과학" },
  { id: "g_xg0709", code: "XG0709", name: "사회학 입문", credits: 3, areaId: "common_core_social", areaName: "공통교양-핵심/사회과학" },
  { id: "g_xg0710", code: "XG0710", name: "법과 인권", credits: 3, areaId: "common_core_social", areaName: "공통교양-핵심/사회과학" },
  { id: "g_xg0711", code: "XG0711", name: "심리학 이해", credits: 3, areaId: "common_core_social", areaName: "공통교양-핵심/사회과학" },
  { id: "g_xg0712", code: "XG0712", name: "대학교양수학", credits: 3, areaId: "common_core_science", areaName: "공통교양-핵심/자연과학" },
  { id: "g_xg0713", code: "XG0713", name: "물리학의 이해", credits: 3, areaId: "common_core_science", areaName: "공통교양-핵심/자연과학" },
  { id: "g_xg0714", code: "XG0714", name: "생활 속의 화학적 사고", credits: 3, areaId: "common_core_science", areaName: "공통교양-핵심/자연과학" },
  { id: "g_xg0715", code: "XG0715", name: "생물학으로의 산책", credits: 3, areaId: "common_core_science", areaName: "공통교양-핵심/자연과학" },
  { id: "g_xg0716", code: "XG0716", name: "지구와 환경", credits: 3, areaId: "common_core_science", areaName: "공통교양-핵심/자연과학" },
  { id: "g_xg0717", code: "XG0717", name: "커뮤니케이션 영어", credits: 2, areaId: "common_global", areaName: "공통교양-글로벌 의사소통" },
  { id: "g_xg0718", code: "XG0718", name: "커뮤니케이션 중국어", credits: 2, areaId: "common_global", areaName: "공통교양-글로벌 의사소통" },
  { id: "g_xg0719", code: "XG0719", name: "커뮤니케이션 일본어", credits: 2, areaId: "common_global", areaName: "공통교양-글로벌 의사소통" },
  { id: "g_xg0720", code: "XG0720", name: "커뮤니케이션 한국어", credits: 2, areaId: "common_global", areaName: "공통교양-글로벌 의사소통" },
  { id: "g_xg0801", code: "XG0801", name: "흙에서 배우는 삶의 지혜", credits: 2, areaId: "common_personality", areaName: "공통교양-인성" },
  { id: "g_xg0966", code: "XG0966", name: "스포츠 활동과 인성 개발", credits: 2, areaId: "common_personality", areaName: "공통교양-인성" },
  { id: "g_xg0983", code: "XG0983", name: "음악하기로배우는삶", credits: 2, areaId: "common_personality", areaName: "공통교양-인성" },

  { id: "g_xg0806", code: "XG0806", name: "한국의 문화 유산", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0807", code: "XG0807", name: "한국고전문학명작산책", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0808", code: "XG0808", name: "한국현대문학의 이해", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0809", code: "XG0809", name: "동양사상의 이해", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0810", code: "XG0810", name: "종교의 이해", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0811", code: "XG0811", name: "현대 대중문화와 예술", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0812", code: "XG0812", name: "문학개론", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0813", code: "XG0813", name: "언어학개론", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0814", code: "XG0814", name: "동양의 역사와 문화", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0815", code: "XG0815", name: "서양의 역사와 문화", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0816", code: "XG0816", name: "현대사회와 스포츠", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0817", code: "XG0817", name: "문화인류학개론", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0818", code: "XG0818", name: "공연예술의 이해", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0819", code: "XG0819", name: "현대예술의 이해", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0820", code: "XG0820", name: "미술의 이해", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0821", code: "XG0821", name: "논리와 사고", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0822", code: "XG0822", name: "예술과 미학", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0823", code: "XG0823", name: "음악으로 세상읽기", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0824", code: "XG0824", name: "동아시아인의 삶과 사상", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0825", code: "XG0825", name: "이공계생을 위한 인문학", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0826", code: "XG0826", name: "패션과 에로티시즘", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0827", code: "XG0827", name: "삼고 중용", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0829", code: "XG0829", name: "정원예술과 문화의 이해", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0722", code: "XG0722", name: "융합 예술로 보는 패션 여행", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0967", code: "XG0967", name: "전남 동부지역의 이해 1", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0968", code: "XG0968", name: "전남 동부지역의 이해 2", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0973", code: "XG0973", name: "시로 읽는 세상", credits: 2, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0974", code: "XG0974", name: "유튜브의 이해", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0984", code: "XG0984", name: "동물라룸메이트", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },
  { id: "g_xg0985", code: "XG0985", name: "만화의이해", credits: 3, areaId: "deep_humanities_arts", areaName: "심화교양-1영역 인문·예술" },

  { id: "g_xg0723", code: "XG0723", name: "경제학개론", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0724", code: "XG0724", name: "커뮤니케이션 회계", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0725", code: "XG0725", name: "사회성 경제를 통한 상생문화", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0726", code: "XG0726", name: "무역문명사의 이해", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0832", code: "XG0832", name: "북한의 정치와 사회", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0833", code: "XG0833", name: "호남의 역사와 문화", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0834", code: "XG0834", name: "다문화사회와 다문화 교육", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0835", code: "XG0835", name: "여성학개론", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0836", code: "XG0836", name: "경영의 이해", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0837", code: "XG0837", name: "직업세계와 법", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0838", code: "XG0838", name: "세계문화를 통한 상관습 엿보기", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0840", code: "XG0840", name: "남도의 정원문화", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0841", code: "XG0841", name: "법학의 이해", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0842", code: "XG0842", name: "정치학의 이해", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0843", code: "XG0843", name: "지리학 탐색", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0844", code: "XG0844", name: "무역을 통한 세상읽기", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0845", code: "XG0845", name: "물류의 이해", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0846", code: "XG0846", name: "지역산업의 이해 1", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0847", code: "XG0847", name: "지역산업의 이해 2", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0848", code: "XG0848", name: "행정학의 이해", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0850", code: "XG0850", name: "학교현장탐구", credits: 1, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0852", code: "XG0852", name: "자유론", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0853", code: "XG0853", name: "도시발전과 지역의 미래", credits: 2, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0854", code: "XG0854", name: "국제개발협력과 글로벌 사회봉사의 이해 I", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0855", code: "XG0855", name: "국제개발협력과 글로벌 사회봉사의 이해 II", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0856", code: "XG0856", name: "국가안보론", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0857", code: "XG0857", name: "북한학", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0858", code: "XG0858", name: "리더십", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0851", code: "XG0851", name: "평생학습진로설계", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0971", code: "XG0971", name: "영화로 이해하는 글로벌 비즈니스", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0986", code: "XG0986", name: "기후변화시대ESG경영의이해", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0987", code: "XG0987", name: "미디어로이해하는기업전략", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0988", code: "XG0988", name: "사회적경제와소셜리빙랩", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },
  { id: "g_xg0989", code: "XG0989", name: "스마트외식과소비자", credits: 3, areaId: "deep_social_region", areaName: "심화교양-2영역 사회·지역" },

  { id: "g_xg0727", code: "XG0727", name: "동물자원과 인간의 생활", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0728", code: "XG0728", name: "자바프로그래밍", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0729", code: "XG0729", name: "파이썬과 컴퓨터 알고리즘", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0730", code: "XG0730", name: "SW를 통한 사회과학 문제해결", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0731", code: "XG0731", name: "이공학도를 위한 매트랩 입문", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0859", code: "XG0859", name: "발명과 특허", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0860", code: "XG0860", name: "생태계와 환경오염", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0861", code: "XG0861", name: "농업의 현재와 미래", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0862", code: "XG0862", name: "생명공학과 인류의 미래", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0863", code: "XG0863", name: "인터넷과 정보윤리", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0864", code: "XG0864", name: "건강과 환경·질병관리", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0865", code: "XG0865", name: "대학수학", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0866", code: "XG0866", name: "일반물리학", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0867", code: "XG0867", name: "일반화학", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0868", code: "XG0868", name: "일반생물학", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0869", code: "XG0869", name: "컴퓨터의 개념 및 실습", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0870", code: "XG0870", name: "지구과학", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0871", code: "XG0871", name: "대학수학 I", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0872", code: "XG0872", name: "대학수학 II", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0873", code: "XG0873", name: "물리학 및 실험 I", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0874", code: "XG0874", name: "물리학 및 실험 II", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0875", code: "XG0875", name: "화학 및 실험 I", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0876", code: "XG0876", name: "화학 및 실험 II", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0877", code: "XG0877", name: "생물학 및 실험 I", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0878", code: "XG0878", name: "생물학 및 실험 II", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0879", code: "XG0879", name: "지구과학 및 실험 I", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0880", code: "XG0880", name: "지구과학 및 실험 II", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0881", code: "XG0881", name: "슬로푸드 이야기", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0882", code: "XG0882", name: "창의적 문제해결 방법론", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0883", code: "XG0883", name: "프레젠테이션 스토리와 발표", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0884", code: "XG0884", name: "IT통합기술과 미래교육", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0886", code: "XG0886", name: "디지털디자인", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0978", code: "XG0978", name: "컴퓨터프로그래밍및실습", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0979", code: "XG0979", name: "데이터 과학 이해", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0889", code: "XG0889", name: "통계학입문", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0890", code: "XG0890", name: "물리학의 세계", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0892", code: "XG0892", name: "식물과 인간의 공생", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0972", code: "XG0972", name: "금융이야기", credits: 2, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },
  { id: "g_xg0980", code: "XG0980", name: "인공지능의 이해", credits: 3, areaId: "deep_science_ict", areaName: "심화교양-3영역 과학·공학·ICT" },

  { id: "g_xg0732", code: "XG0732", name: "영어읽기와 프리젠테이션", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0733", code: "XG0733", name: "영어읽기와 글쓰기", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0734", code: "XG0734", name: "한일(韓·日) 대중문화의 이해를 통한 소통", credits: 2, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0893", code: "XG0893", name: "비판적 사고와 글쓰기", credits: 2, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0894", code: "XG0894", name: "인문사회과학 글쓰기", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0895", code: "XG0895", name: "자연과학 글쓰기", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0896", code: "XG0896", name: "영어작문", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0897", code: "XG0897", name: "중국어입문1", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0898", code: "XG0898", name: "중국어입문2", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0899", code: "XG0899", name: "일본어입문1", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0900", code: "XG0900", name: "일본어입문2", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0901", code: "XG0901", name: "비즈니스영어1", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0902", code: "XG0902", name: "비즈니스영어2", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0903", code: "XG0903", name: "대학영어", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0904", code: "XG0904", name: "영어회화", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0905", code: "XG0905", name: "대학한문", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0906", code: "XG0906", name: "영어회화1", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0907", code: "XG0907", name: "영어회화2", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0909", code: "XG0909", name: "TED를 통해 배우는 커뮤니케이션", credits: 2, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0910", code: "XG0910", name: "대학글쓰기", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0911", code: "XG0911", name: "대학글쓰기 I", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0912", code: "XG0912", name: "대학글쓰기 II", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0913", code: "XG0913", name: "기초중국어", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0914", code: "XG0914", name: "기초일본어", credits: 3, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0915", code: "XG0915", name: "영화와 토론", credits: 2, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0916", code: "XG0916", name: "생활일본어회화", credits: 2, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },
  { id: "g_xg0917", code: "XG0917", name: "생활중국어회화", credits: 2, areaId: "deep_communication_language", areaName: "심화교양-4영역 의사소통·외국어" },

  { id: "g_xg0735", code: "XG0735", name: "인문학과 자연과학의 만남", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0918", code: "XG0918", name: "생명·환경·정보 윤리", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0919", code: "XG0919", name: "유전과 진화의 이해", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0920", code: "XG0920", name: "식품과 건강", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0921", code: "XG0921", name: "인류생활과 환경이슈", credits: 3, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0923", code: "XG0923", name: "영상으로 보는 이기경험과 학습", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0924", code: "XG0924", name: "스마트 의류 디자인", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0925", code: "XG0925", name: "혁명을 꿈꾸는 미생물", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0927", code: "XG0927", name: "미래사회의 예측과 변화", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0928", code: "XG0928", name: "환경호르몬의 역습", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0929", code: "XG0929", name: "기후변화와 녹색도시", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0930", code: "XG0930", name: "에코지능과 지속가능한 미래", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0931", code: "XG0931", name: "숲과 문화와 산림치유", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0932", code: "XG0932", name: "문명과 함께하는 기술", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0933", code: "XG0933", name: "과학과 디자인이 함께하는 3D프린팅", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0934", code: "XG0934", name: "과학사의 뒷이야기와 현대문화", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0935", code: "XG0935", name: "아시아공동체론", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0936", code: "XG0936", name: "소비와 윤리", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0937", code: "XG0937", name: "과학기술 세상에서의 삶", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0938", code: "XG0938", name: "영화와 책속의 생명과학 이야기", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0939", code: "XG0939", name: "세상을 바꾼 천연물 이야기", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0940", code: "XG0940", name: "지구환경과 숲의 역할", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0941", code: "XG0941", name: "10억달러분자", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0942", code: "XG0942", name: "스마트농식품산업입문", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0943", code: "XG0943", name: "역사속의 과학이야기", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0944", code: "XG0944", name: "신기한 식물세계와 인류역사 이야기", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0945", code: "XG0945", name: "여행보건학", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0946", code: "XG0946", name: "코딩과 융복합 교육", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0948", code: "XG0948", name: "미래융합시대 메가트렌드", credits: 3, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0949", code: "XG0949", name: "과학,인간,기술,사회의 이해", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0950", code: "XG0950", name: "4차 산업혁명 기술창업", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0951", code: "XG0951", name: "4차 산업혁명과 푸드테크 창업", credits: 2, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0969", code: "XG0969", name: "행복한 뇌와 불타는 뉴런", credits: 3, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0975", code: "XG0975", name: "한약과 건강", credits: 3, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },
  { id: "g_xg0970", code: "XG0970", name: "공존의 심리학", credits: 3, areaId: "deep_convergence", areaName: "심화교양-5영역 융·복합" },

  { id: "g_xg0736", code: "XG0736", name: "인간뇌과학을 통한 자기개발", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0952", code: "XG0952", name: "자기개발과 진로설정", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0953", code: "XG0953", name: "취업과 진로", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0976", code: "XG0976", name: "글로벌 벤처창업1", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0955", code: "XG0955", name: "창업과 진로 I", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0981", code: "XG0981", name: "창업가정신", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0977", code: "XG0977", name: "글로벌 벤처창업2", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0958", code: "XG0958", name: "창업과 진로 II", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0982", code: "XG0982", name: "기업가정신", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0960", code: "XG0960", name: "인성교육론", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0961", code: "XG0961", name: "창업경영의 이해 I", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0962", code: "XG0962", name: "창업경영의 이해 II", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0963", code: "XG0963", name: "창의적 창업 아이디어 개발", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0964", code: "XG0964", name: "창업의 이해", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
  { id: "g_xg0965", code: "XG0965", name: "기업직무의 이해", credits: 2, areaId: "deep_self_development", areaName: "심화교양-6영역 자기개발" },
];

// 컴퓨터공학과 2022학번 교양 최소 이수요건.
// 자연과학 영역은 최소 이수학점이 없어 areaMinimums에 포함하지 않는다.
export const generalEducationRequirements22: GeneralEducationRequirements = {
  commonRequiredCredits: 15,
  advancedRequiredCredits: 15,
  advancedRequiredCourses: [
    { code: "XG0728", name: "자바프로그래밍", credits: 3 },
    { code: "XG0869", name: "컴퓨터의 개념 및 실습", credits: 3 },
  ],
  requiredCourses: [
    { code: "XG0800", name: "대학생활과 목표설정", credits: 1 },
    { code: "XG0700", name: "독서와 표현", credits: 2 },
  ],
  oneOfCourseGroups: [
    {
      id: "foundation_thinking",
      label: "사고와 글쓰기 또는 정량적사고와 컴퓨팅사고",
      codes: ["XG0701", "XG0702"],
      credits: 2,
    },
  ],
  areaMinimums: [
    { areaId: "common_core_humanities", label: "핵심 / 인문학", credits: 3 },
    { areaId: "common_core_social", label: "핵심 / 사회과학", credits: 3 },
    { areaId: "common_global", label: "글로벌의사소통", credits: 2 },
    { areaId: "common_personality", label: "인성", credits: 2 },
  ],
  advancedAreaPrefix: "deep_",
};

export const certificationAreas22: CertificationArea[] = [
  {
    id: "personality_art_pe",
    name: "① 인성·예술·체육 분야",
    score: 0,
    description:
      "다음 중 1가지 이상 참가(각 향림포인트 100점 이상): 인성개발프로그램 참가 / 상담활동 참가(진로·심리·취업·학습법 등) / 예술체육 특기개발 활동 참가 / 문화예술 활동 참가",
  },
  {
    id: "volunteer",
    name: "② 지역·해외봉사 분야",
    score: 0,
    description: "사회봉사활동 80시간 이상 (향림포인트 '사회 및 해외봉사활동' 100점 이상)",
  },
  {
    id: "computer_literacy",
    name: "③ 컴퓨터·정보화 분야",
    score: 0,
    description:
      "국내외 컴퓨터 관련 자격증 취득: 컴퓨터활용능력 1급, 사무자동화산업기사, 정보처리산업기사, MOS, ICDL 등 (향림포인트 '컴퓨터정보화 자격증 취득 활동' 100점 이상)",
  },
  {
    id: "language_cert",
    name: "④ 외국어 분야",
    score: 0,
    description:
      "영어 TOEIC 500점 이상 / 일본어 JPT 500점 이상 / 중국어 HSK 6급(신HSK 5급 180~194점) 이상 (그 외 외국어는 공인어학성적 환산표 적용, 향림포인트 '외국어성적' 4등급(100점) 이상)",
  },
];

export const certificationRule22 =
  "순천대학교 졸업자격 인증제 운영 지침(2015.5.18 제정, 2019.11.28 개정) 제3조: 4개 영역 중 1개 영역 이상 선택하여 인증 (여러 영역 점수 합산 불가). 각 영역 향림취업향상포인트 100점 이상이면 인증.";

export function buildRequirements(
  admissionYear: number,
  school = DEFAULT_SCHOOL,
  department = DEFAULT_DEPARTMENT
): Requirements {
  // TODO: 추후 학번별로 실제 교육과정이 다르면 연도별 템플릿을 분리할 것.
  // 지금은 2022학번 자료만 검증되어 있고, 다른 학번은 같은 템플릿을 임시로 재사용한다.
  return {
    school,
    department,
    admissionYear,
    isVerified: admissionYear === 2022 && department === DEFAULT_DEPARTMENT,
    totalCreditsRequired: 130,
    generalCreditsRequired: 30,
    generalSelectionCreditLimit: 20,
    majorCreditsRequired: 70,
    majorRequiredCreditsRequired: 36,
    majorCourses: majorCourses22,
    generalCourseCatalog: generalCourses22,
    generalEducationRequirements: generalEducationRequirements22,
    certificationRule: certificationRule22,
    certificationAreas: certificationAreas22.map((a) => ({ ...a })),
  };
}
